export const items = [
  {
    id: "1",
    productName: "Test Product 1",
    price: 100,
    stock: 50,
    category: "Clothing",
    color: "Red",
    material: "Cotton",
    size: "M",
    image: "http://example.com/product1.jpg",
  },
  {
    id: "2",
    productName: "Test Product 2",
    price: 200,
    stock: 30,
    category: "Accessories",
    color: "Blue",
    material: "Leather",
    size: "L",
    image: "http://example.com/product2.jpg",
  },
  {
    id: "3",
    productName: "Test Product 3",
    price: 300,
    stock: 20,
    category: "Footwear",
    color: "Black",
    material: "Rubber",
    size: "S",
    image: "http://example.com/product3.jpg",
  },
];
export const item = {
  id: "1",
  productName: "Test Product 1",
  price: 100,
  stock: 50,
  category: "Clothing",
  color: "Red",
  material: "Cotton",
  size: "M",
  image: "http://example.com/product1.jpg",
};
